(defun inspiration-844431 ()
  "Theme generated by Sweyla: http://inspiration.sweyla.com/code/seed/844431/"
  (interactive)
  (color-theme-install
   '(inspiration-844431
     ((background-color . "#000007")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#D00095"))))
     (font-lock-constant-face ((t (:foreground "#A4570C"))))
     (font-lock-builtin-face ((t (:foreground "#745899"))))
     (font-lock-function-name-face ((t (:foreground "#E6001F"))))
     (font-lock-variable-name-face ((t (:foreground "#EC0000"))))
     (font-lock-keyword-face ((t (:foreground "#00D192"))))
     (font-lock-string-face ((t (:foreground "#B8AE3B"))))
     (font-lock-doc-string-face ((t (:foreground "#B8AE3B"))))
     (font-lock-type-face ((t (:foreground "#6D537E"))))
     )))

(provide 'inspiration-844431)